# Generated by Django 5.1.5 on 2025-02-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnPeak', '0003_remove_question_quiz_remove_submission_assignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
