# Generated by Django 5.1.5 on 2025-02-01 15:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnPeak', '0006_alter_enrollment_enrollment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
